version: 2.1

jobs:
  build:
    docker:
    - image: fpco/stack-build:lts-13.16
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Install Docker
        command: "./scripts/install-docker.sh"
    - restore_cache:
        name: Restore cached dependencies
        keys:
          - v2_haskell-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}-{{ checksum "repo-tools.cabal" }}
          - node_modules-{{ checksum "frontend/package.json" }}-{{ checksum "frontend/package-lock.json" }}
    - run:
        name: Resolve/Update Dependencies
        command: stack install --only-dependencies
    - save_cache:
        name: Cache Haskell dependencies
        key: v2_haskell-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}-{{ checksum "repo-tools.cabal" }}
        paths:
          - ~/.stack
          - ~/.stack-work

    - run:
        name: Install Node.js and npm
        command: "curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - && apt install -y nodejs"
    - run:
        name: npm install
        command: "cd frontend && npm install"
    - save_cache:
        name: Cache Node.js dependencies
        key: node_modules-{{ checksum "frontend/package.json" }}-{{ checksum "frontend/package-lock.json" }}
        paths:
          - frontend/node_modules
    - run:
        name: npm run build
        command: "cd frontend && npm run build"
    - run:
        name: webpack
        command: "cd frontend && npm run webpack:production"
    - run:
        name: stack build
        command: "stack build -j1"
    - run:
        name: Build a Docker image
        command: "docker build -t navikt/repo-tools:$CIRCLE_SHA1 ."
    - run:
        name: Archive Docker image
        command: "docker save -o image.tar navikt/repo-tools:$CIRCLE_SHA1"
    - persist_to_workspace:
        root: .
        paths:
          - ./image.tar

  deploy:
    docker:
    - image: circleci/node:11.12
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | base64 --decode | docker login -u "$DOCKER_USER" --password-stdin
      - run:
          name: Push the Docker image
          command: "docker push navikt/repo-tools:$CIRCLE_SHA1"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
